# Generated by Django 5.2 on 2025-04-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_file_delete_binarydocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='last_modified',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
